language: python

python:
      - "3.5"

install:
      - "python setup.py install"
          - "pip install codecov"

script:
      - "coverage run tests/test_cooccurran.py"

after_success:
      - "codecov"
