name: Security Scan

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggers
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[security]"
          pip install pip-audit pip-licenses

      - name: Run Bandit Security Scan
        continue-on-error: true
        run: |
          bandit -r asymcat/ -f sarif -o bandit-results.sarif
          bandit -r asymcat/ -f json -o bandit-results.json

      - name: Upload Bandit SARIF Results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-results.sarif
          category: bandit

      - name: Run Safety Check
        continue-on-error: true
        run: |
          safety check --json --output safety-results.json
          safety check --audit-and-monitor --api-key=${{ secrets.SAFETY_API_KEY || '' }}

      - name: Run Pip Audit
        continue-on-error: true
        run: |
          pip-audit --format=json --output=pip-audit-results.json
          pip-audit --format=sarif --output=pip-audit-results.sarif

      - name: Upload Pip Audit SARIF Results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit-results.sarif
          category: pip-audit

      - name: Check License Compatibility
        run: |
          pip-licenses --format=json --output-file=licenses.json
          pip-licenses --fail-on="GPL,AGPL,LGPL" || echo "Warning: Potential license issues detected"

      - name: Upload Security Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            bandit-results.json
            bandit-results.sarif
            safety-results.json
            pip-audit-results.json
            pip-audit-results.sarif
            licenses.json
          retention-days: 30

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, PSF-2.0

  codeql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"